### ISSUE TITLE
infografia-de-calidad

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/infografia-de-calidad-bjny-huerto#1]
[Infografía Calidad de Software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-bjny-huerto/files/8790692/Infografia.Calidad.de.Software.pdf)

**Comment by christopheremv** [comment]
calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
