### ISSUE TITLE
Infografia Jazmin Lopez Riveros

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/infografia-de-calidad-bjny-huerto#3]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-bjny-huerto/files/8904314/Infografia.pdf)

**Comment by christopheremv** [comment]
calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
