### ISSUE TITLE
Infografía Calidad de Software Yabin

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/infografia-de-calidad-bjny-huerto#4]
Anexo infografia.
[Infografía de Proceso Calidad de Software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-bjny-huerto/files/8911652/Infografia.de.Proceso.Calidad.de.Software.pdf)

**Comment by christopheremv** [comment]
calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
